apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-appset-app
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "openshift-gitops"
  source:
    repoURL: 'https://github.com/yosuke312/sre-argo-apps'
    targetRevision: HEAD
    path: nginx-appset-helm
    helm:
      releaseName: nginx-appset
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
