apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/yosuke312/sre-argo-apps
      revision: HEAD
      files:
      - path: nginx/kingdom-configs/*.yaml
  template:
    metadata:
      name: {{ `"{{ cluster.name }}-nginx"` }}
    spec:
      project: default
      destination:
        namespace: {{ `"{{ cluster.namespace }}"` }}
        server: {{ `"{{ cluster.server }}"` }}
      sources:
      - repoURL: 'https://github.com/yosuke312/sre-argo-apps'
        targetRevision: HEAD
        path: nginx
        helm:
          releaseName: nginx
          valueFiles:
          - {{ `"$values/nginx/kingdom-configs/{{ cluster.name }}.yaml"` }}
      - repoURL: https://github.com/yosuke312/sre-argo-apps
        targetRevision: HEAD
        ref: values

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

