apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-appset
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/yosuke312/sre-argo-apps
      revision: HEAD
      files:
      - path: kingdom-configs/*.yaml
  template:
    metadata:
      name: {{ `"{{ .cluster.name }}-nginx-app"` }}
    spec:
      project: default
      destination:
        namespace: {{ `"{{ .cluster.namespace }}"` }}
        server: {{ `"{{ .cluster.server }}"` }}
      source:
        repoURL: 'https://github.com/yosuke312/sre-argo-apps'
        targetRevision: HEAD
        path: nginx-helm-chart
        helm:
          debug: true
          releaseName: nginx
          valueFiles:
          - {{ `"../kingdom-configs/{{ .cluster.name }}.yaml"` }}

      {{ printf "{{- if .cluster.autoSync  }}"}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      {{ printf "{{- end }}"}}

