apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/yosuke312/sre-argo-apps
      revision: master
      files:
      - path: nginx/kingdoms/*.json
  template:
    metadata:
      name: {{ `"{{ cluster.name }}-nginx"` }}
    spec:
      project: default
      destination:
        namespace: {{ `"{{ cluster.namespace }}"` }}
        server: {{ `"{{ cluster.server }}"` }}
      source:
        repoURL: 'https://github.com/yosuke312/sre-helm-charts'
        targetRevision: 0.11.0a
        path: nginx
        helm:
          releaseName: nginx
          valueFiles:
          - {{ `"kingdom-configs/{{ cluster.name }}.yaml"` }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

